project: 
  type: website
  output-dir: docs


website: 
  title: "Tarea_2_ Análisis y Visualización de Datos"
  navbar: 
    left: 
      - href: index.qmd
        text: Home
      - href: viz.qmd
        text: Visualization


format:
  html:
    theme: cosmo
    toc: true